### ISSUE TITLE
Using stmia in the mempcy as well as memset

### ISSUE THREAD

**Issue by richardgroves** [simonjhall/copies-and-fills#1]
Memset uses:

stmia r0!, {r1, r4, r5, r6}
stmia r0!, {r7, r8, r9, r10}

to store the data out, where as mempcy uses:

```
    str r4, [r0], #4
str r5, [r0], #4
str r6, [r0], #4
str r7, [r0], #4
str r8, [r0], #4
str r9, [r0], #4
str r10, [r0], #4
```

It appears to me they do the same thing, but one in less instructons - no idea of the timings, but smaller code should be worth it even if the timing is equal. Not sure if there is a load-multiple that could replace the loads as well. Also there appear to be just 7 load/stores in that area?

Hmmm...just noticed this is a bit of code on the wrong side of a #if 1 - I'll get back in my cave.

**Comment by simonjhall** [comment]
Don't forget about r1! The stmia store eight registers (32 bytes), the strs
only store seven (28 bytes).
Although just before checking in the code I realised that I was writing out
eight discreet registers that all have the same value. I could have just
written out r1, r4, r5, r6 twice. This might be faster or slower.

On 2 July 2012 12:06, Richard Groves <
reply@reply.github.com

**Comment by richardgroves** [comment]
That is what I was wondering about - looked like the memcpy code was just storing 28 bytes out. Why?

Can the stmia use the same register in all slots? ie. is 'stmia r0!, {r1, r1, r1, r1}' valid? Then you can save a load of setup on the store values - just do that instruction twice (can't be any slower to read the same register on any sane CPU ISA).

**Comment by simonjhall** [comment]
Btw for the strs are you talking about line ~103 in memcpy? That was a test for the misaligned case. We're at least 4 bytes misaligned - hence only seven loads/stores - so the previous dash of code computes the misalignment and then jumps past the nops to the correct number of ldr/str instructions. "add pc, pc, r3"

In the end if was just quicker to do a loop until we're 32 byte aligned.

**Comment by richardgroves** [comment]
Ah! Ok - was those lines I was looking at. Trying to get a handle on which path was quicker. Is there any benefit on also building an 'aligned memcpy' that can assume destination alignment, at least, and maybe src too? Can't add much to the code size and then those in the know can take the fast path.

**Comment by simonjhall** [comment]
> Can the stmia use the same register in all slots? ie. is 'stmia r0!, {r1, r1, r1, r1}' valid? 

Afraid not. Each register used is a bit in a bitmask in the instruction encoding. To run the instruction it walks the bitmask from low to high. ie stmia {r1, r2, r3} is the same as stmia {r3, r2, r1} and since a bit can only be set once, you can't do stmia {r1, r1, r1}

**Comment by richardgroves** [comment]
Shame. Looks like a nice instruction though and I now see where you use it in the core memcpy loop to do the heavy work. Did you do any further unrolling to reduce the loop cost or does that just run out of registers too quickly and involve too much pre-code? Might be a fun test to see what the maximum speed is if both src+dest are (say) 1k aligned.

One other thing - the pld [r1, #128] at line 139 - does that have the potential to read beyond the end of the source data? Could that trigger a page violation, or are pld safe from that?

**Comment by simonjhall** [comment]
Have a lookie at this
http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.faqs/ka3934.html
Dunno if GCC calls it or not...it's defined in the EABI so it's there for it to use!

Btw did you know memcpy and memset require you to return the original dest pointer? Irritating. Why would you want that? Looks like they scrapped that in the EABI versions. They have void returns.

> Did you do any further unrolling to reduce the loop cost

I tried up to 64 bytes at a time, but no interesting change. I tried doing different operations and it seems that 32 byte load/store (with store destination being 32b aligned) gives the best result for memcpy. Yet memset gets 30% faster with sequential 16b stores...

> the pld

Yes it will read beyond the end of the buffer. The docs say it can't cause any synchronous abort to occur but I should double check just to be sure!
The unaligned copy path will do a proper overfetch by up to three bytes though beyond the end of the buffer. However I don't think you can set access permissions on anything less than 4k byte buffers on ARM Linux (certainly not on the byte level) so I'm ok with that. libc memcpy has the same <=3 byte overfetch too on misaligned data.

**Comment by richardgroves** [comment]
So it looks like you have to do the _aeabi versions too if you wanted to replace the library...fun.

Had figures that a few bytes over the end of the buffer would be ok (and standard) given page size alignment, but 128 could be pushing it a bit. Be a shame to have to deal with it, but....

**Comment by simonjhall** [comment]
Nah, let it abort :)
If you do have the machine in front of you, try adding this to the very beginning of memcpy and run something - see if it faults. (untested code)

memcpy:
   push {r0}
   mov r0, #0
   pld [r0]
   sub r0, #4
   pld [r0]
   pop {r0}
   <the original code>

**Comment by richardgroves** [comment]
As I said on facebook I don't have any test code to use the library - not even sure of the incantation I'd need to get it to link to the library that it builds. Do have machine in front of me (well - to one side, but the SSH into it is on this desktop ;-)

**Comment by simonjhall** [comment]
Running make on just my code should build the my library as a shared
object, libcofi_rpi.so.
Then to test, try:
LD_PRELOAD="/full/path/to/libcofi_rpi.so" any_program_name_eg_Xorg

alternatively:
export LD_PRELOAD=/full/path/to/libcofi_rpi.so
any_program_that_calls_memcpy_or_memset

LD_PRELOAD in env makes any subsequent program pick up my memcpy and memset
over the libc one.

On 2 July 2012 13:06, Richard Groves <
reply@reply.github.com

**Comment by richardgroves** [comment]
Ok, that extra few instructions at the start of the code doesn't cause a problem - so looks like doing a pld on protected addresses is fine.

Making the added code:

push {r0}
    mov r0, #0
    pld [r0]
    ldr r3, [r0]
    sub r0, #4
    pld [r0]
    pop {r0}

does cause a segmentation fault, so pretty conclusive that PLD is nice and safe.

**Comment by simonjhall** [comment]
Sur-weet. Thanks for testing. Ship it...

On 2 July 2012 13:46, Richard Groves <
reply@reply.github.com

**Comment by simonjhall** [comment]
I've changed the main loops to be slightly better, and no extra registers used in memset.
