### ISSUE TITLE
Problems during emulation with qemu

### ISSUE THREAD

**Issue by bendavis78** [simonjhall/copies-and-fills#4]
I'm not sure if this has been addressed yet, but I know raspbian includes this library and loads it by default. When using qemu to emulate a raspbian environment, you have to comment out the line in /etc/ld.so.preload that loads libcofi_rpi.so (any tutorial for using qemu-user with raspbian will tell you to do this).

Commenting out a line is easy enough, except that you have to remember to uncomment it when you're done working in the emulated environment.

Is there a way make this library qemu-safe?

**Comment by simonjhall** [comment]
What's the problem with it? There's nothing dodgy that it does - if there's an issue it should be fixed in qemu!
EDIT: do you have anything like a callstack or errors?

**Comment by bendavis78** [comment]
qemu segfualts, basically. I did see that there is a fork of qemu being worked on specifically for the rpi, so they may have a fix for it.

**Comment by simonjhall** [comment]
Interesting - would you happen to know of a qemu tracker where they might be looking into it? As I say, there's nothing dodgy in there. It's often that ARMv6 support is a bit patchy in many applications. Is this with JIT emulation? If so, can you try with the slow/reliable emulation?

**Comment by simonjhall** [comment]
Hi again - I've just dug this up: http://www.raspberrypi.org/forums/viewtopic.php?f=72&t=26561&start=50
They've taken my code and forked it, and added an extra function (memcmp). This is the function that is faulting. As the crash is a problem of qemu + their code, may I close this issue?

**Comment by bendavis78** [comment]
Ah OK, I have seen that thread. Yes go ahead and close, sorry for the
confusion.
